// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-6_FDFhOWME-BefwEzXzgJjFUjkkfXWA',
    appId: '1:15492932583:web:4e06746f99827438fe9342',
    messagingSenderId: '15492932583',
    projectId: 'movies-app-673a0',
    authDomain: 'movies-app-673a0.firebaseapp.com',
    storageBucket: 'movies-app-673a0.firebasestorage.app',
    measurementId: 'G-LSZ7EFNCZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6WqW0CB2ZUhQTE7nONC5E3AP3UFgfjis',
    appId: '1:15492932583:android:12c8c5059f263026fe9342',
    messagingSenderId: '15492932583',
    projectId: 'movies-app-673a0',
    storageBucket: 'movies-app-673a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArxQQu-9cMWmBKf3QEQ6FD7VbiWYOarTM',
    appId: '1:15492932583:ios:23b80e94bd7ccf96fe9342',
    messagingSenderId: '15492932583',
    projectId: 'movies-app-673a0',
    storageBucket: 'movies-app-673a0.firebasestorage.app',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArxQQu-9cMWmBKf3QEQ6FD7VbiWYOarTM',
    appId: '1:15492932583:ios:23b80e94bd7ccf96fe9342',
    messagingSenderId: '15492932583',
    projectId: 'movies-app-673a0',
    storageBucket: 'movies-app-673a0.firebasestorage.app',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-6_FDFhOWME-BefwEzXzgJjFUjkkfXWA',
    appId: '1:15492932583:web:813e44fd84694922fe9342',
    messagingSenderId: '15492932583',
    projectId: 'movies-app-673a0',
    authDomain: 'movies-app-673a0.firebaseapp.com',
    storageBucket: 'movies-app-673a0.firebasestorage.app',
    measurementId: 'G-LFEHZZ0MCW',
  );
}
