import 'package:dio/dio.dart';
import '../models/movie_model.dart';

abstract class MovieRemoteDataSource {
  Future<Autogenerated> getMovies({
    int page = 1,
    String? genre,
  });
}

class MovieRemoteDataSourceImpl implements MovieRemoteDataSource {
  final Dio dio;

  MovieRemoteDataSourceImpl({
    required this.dio,
  });

  @override
  Future<Autogenerated> getMovies({
    int page = 1,
    String? genre,
  }) async {
    final response = await dio.get(
      'list_movies.json',
      queryParameters: {
        'page': page,
        'limit': 20,
        if (genre != null) 'genre': genre,
      },
    );

    return Autogenerated.fromJson(response.data);
  }
}