import 'package:dio/dio.dart';
import 'package:movieapp/features/movies/data/models/movie_model.dart';

abstract class SearchRemoteDataSource {
  Future<Autogenerated> searchMovies({
    required String query,
    int page = 1,
  });
}

class SearchRemoteDataSourceImpl implements SearchRemoteDataSource {
  final Dio dio;

  SearchRemoteDataSourceImpl({
    required this.dio,
  });

  @override
  Future<Autogenerated> searchMovies({
    required String query,
    int page = 1,
  }) async {
    final response = await dio.get(
      'list_movies.json',
      queryParameters: {
        'query_term': query,
        'page': page,
        'limit': 20,
      },
    );

    return Autogenerated.fromJson(response.data);
  }
}